baseURL = "http://gboncoffee.github.io/"
languageCode = "en-us"
title = "Gabriel G. de Brito"
theme = "hugo-theme-notrack"
mainSections = ["projects", "posts", "literature"]
paginate = 50
summaryLength = 1

[params]
  author = "Gabriel G. de Brito"
  favicon = "profile.png"
  showBlogLatest = false
  mainSections = ["projects", "posts", "literature"]
  showTaxonomyLinks = false
  footer = "© Gabriel G. de Brito (CC-BY-NC)"

  [params.social]
    github = "gboncoffee"
    linkedin = "gboncoffee"
    email = "gabrielgbrito@icloud.com"
    twitter = "gboncoffee"
    instagram = "gboncoffee"
    youtubechannel = "gboncoffee"
    steam = "gboncoffee"

[[menu.main]]
  name = "Me"
  pageRef = "/"
  weight = 10
[[menu.main]]
  name = "Projects"
  pageRef = "/projects"
  weight = 20
[[menu.main]]
  name = "Posts"
  pageRef = "/posts"
  weight = 30
[[menu.main]]
  name = "Literature"
  pageRef = "/literature"
  weight = 40
